name: ashva_fitness_example
description: Demonstrates how to use the ashva_fitness plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0+4
  fit_kit: 1.1.1

  percent_indicator: ^2.1.1
  font_awesome_flutter: ^8.4.0
  connectivity: 0.4.6+2
  
  flutter_appavailability:
    git:
      url: "https://github.com/bwhiteTP/flutter_appavailability.git"
      ref: "26461d5296cd8c0a58da1d9c5f1e960643ebb323"
  launch_review: ^1.0.1
  open_appstore: 1.0.2
  rflutter_alert: ^1.0.3
  shared_preferences: 0.5.6+2
  video_player: ^0.8.0
  curved_navigation_bar: ^0.3.1 #latest version
  datetime_picker_formfield: 1.0.0
  strava_flutter: 1.2.0+45
  html: ^0.14.0+3 # to remove the # at the end of the redirect url
  path_provider: ^1.5.1 # To access to the gpx file used to upload
  readmore:
  fluttertoast:
  bmnav:
  image_picker: 0.6.2+3
  image_cropper:
  pin_code_fields:
  timer_count_down:
  share:
  flutter_email_sender:
  provider:
  calendar_strip:
  flutter_markdown:
  upi_pay:
  flutter_splash:
  flutter_plugin_android_lifecycle: ^1.0.4
  screenshot: ^0.1.1
  esys_flutter_share: ^1.0.2
  page_transition:
  flare_splash_screen:
  bezier_chart:
  intl:
  material_design_icons_flutter: 4.0.5345
  fancy_drawer:
  table_calendar:
  slide_countdown_clock: ^1.0.3
  flutter_rating_bar: ^3.0.1+1
  adobe_xd:
  liquid_progress_indicator:
  charts_flutter: ^0.9.0
  shape_of_view:
  cached_network_image:
  photo_view:
  fl_chart:
  dio:
  rounded_flutter_datetime_picker: ^1.3.11
  flutter_svg: ^0.18.1
  http_parser:
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  ashva_fitness:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/ashva_white_logo.jpeg
    - assets/img/road-running.jpg
    - assets/img/road_running.jpeg
    - assets/img/bolt.png
    - assets/img/down_orange.png
    - assets/img/fish.png
    - assets/img/illustration.png
    - assets/img/sausage.png
    - assets/img/shoe.png
    - assets/img/up_red.png
    - assets/img/ashvalogo.png
    - assets/img/bg.jpg
    - assets/img/ashva_white_logo.png
    - assets/videos/aeologic_logo.mp4
    - assets/img/powered_by.png
    - assets/img/source.gif
    - assets/img/profile_pic.jpg
    - assets/img/profile_pic.png
    - assets/img/motivation.png
    - assets/Images/
    - assets/flare/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas_regular.otf
        - asset: assets/fonts/bebas_bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family:  BadgeIcons
      fonts:
        - asset: assets/fonts/BadgeIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
